#!/bin/bash
#
# Created: Oct 28, 2020.
# see: MIT License.
#

set -eu
#set -x

# see:
#   https://misc.flogisoft.com/bash/tip_colors_and_formatting
#   https://gist.github.com/leiless/408b978965fc76b3c41b837811a475d2
GRN="$(tput setaf 10)"
RST="$(tput sgr0)"

# xx used for tracing command, useful for presentation and debugging.
xx() {
    echo -en "+ $GRN"
    echo -n $@
    echo -e "$RST"
    "$@"
}

setup_pf_table() {
    #URL=https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt
    URL=https://cdn.jsdelivr.net/gh/17mon/china_ip_list@master/china_ip_list.txt
    NAME="$(basename "$URL")"
    xx curl -fsSL "$URL" -o "$NAME"
    # Add a trailing linefeed for later file concatenation
    echo >> "$NAME"

    cat << EOL > lan_ip_list.txt
0.0.0.0/8
10.0.0.0/8
127.0.0.0/8
169.254.0.0/16
172.16.0.0/12
192.168.0.0/16
224.0.0.0/4
240.0.0.0/4
EOL

    rm -f proxy_ip_list.txt
    for IP in "$@"; do
        echo $IP >> proxy_ip_list.txt
    done

    cat *_ip_list.txt > direct.txt
    mkdir -p /var/tmp/pf
    cp direct.txt /var/tmp/pf

    cat << EOL > /var/tmp/pf/pf.conf
#
# This pf.conf generated by pf-setup.sh
#

table <direct> persist file "/var/tmp/pf/direct.txt"
rdr pass on lo0 proto tcp from any to !<direct> -> 127.0.0.1 port 12345
pass out route-to (lo0 127.0.0.1) proto tcp from any to !<direct>

EOL

    xx sudo pfctl -e || true
    xx sudo pfctl -F all
    xx sudo pfctl -f /var/tmp/pf/pf.conf

    xx sudo pfctl -vvvs Tables
    xx sudo pfctl -vvvs nat
    xx sudo pfctl -vvvs rules
}

is_ipv4() {
    if [ $# -ne 1 ]; then
        echo "ERROR: expected one argument"
        return 1
    fi
    echo "$1" | grep -Eq "^[0-9]{1,3}(\.[0-9]{1,3}){3}$"
}

usage() {
    cat << EOL
Usage:
    $(basename "$0") IPv4...

EOL
    exit "$1"
}

if [ $# -eq 0 ]; then
    usage 1
fi

# see: https://stackoverflow.com/questions/2761723/what-is-the-difference-between-and-in-shell-scripts
for IP in "$@"; do
    if ! is_ipv4 "$IP"; then
        usage 1
    fi
done

cd "$(dirname "$0")"

# Ask sudo privilege in advance, will cache later.
sudo printf ""

xx setup_pf_table "$@"

